piVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: kc-spring-demo
spec:
  replicas: 2  # 복제본 갯수
  selector:
    matchLabels:
      app: kc-spring-demo
  template:
    metadata:
      labels:
        app: kc-spring-demo
    spec:
      containers:
      - name: kc-webserver
        image: kakaocloud.kr-central-2.kcr.dev/kakao-k8s-repo-t/demo-spring-boot:latest
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred  # NCR에 저장된 이미지 Pulling을 위한 인증 Secret 값
